### ISSUE TITLE
How do you detect end of data

### ISSUE THREAD

**Issue by Praveena0989** [G6EJD/ESP32-Using-Hardware-Serial-Ports#1]
Hello David,

I am able to use your code on dust sensor but I am getting data in sequence and in that case how do you detect the end of the sequence?

**Comment by G6EJD** [comment]
This is not a software issue rather a serial class usage issue. You can determine the end of the data stream or at least an empty buffer using the serial.available() property but a lot depends on the sensor, I would be very surprised if the sensor did not issue and end of reading/data marker have you checked the data sheet or printed out the received characters in hex or decimal to see it might be something as simple as a carriage return to denote end of reading.

**Comment by Praveena0989** [comment]
Thank you so much for the instant reply. I am using this [sensor](https://sensing.honeywell.com/honeywell-sensing-hpm-series-particle-sensors-datasheet-32322550-e-en.pdf). It sends data in 32 bytes protocol. 
`void loop() { 
  while (Serial2.available()) {
    Serial.print(int(Serial2.read()));
  }
  delay(10000);
}`

I am giving 10s delay just to make sure that print is happening in a single while. I am getting 96 bytes value but it is 32-byte value repeated thrice.

**Comment by G6EJD** [comment]
I’ll check but the sensor is sending 16-bit reasons (2-bytes) so you need to be reading 16-but int from the device - maybe. I’ll look.

**Comment by G6EJD** [comment]
OK, so confirmed it a 32-byte protocol output, Two separate header bytes then 30 reading bytes structured as 15 16-bit values.

I think what your seeing is 3 readings but I don’t know if you’ve communicated with the sensor correctly according to the protocol?

Maybe turn off auto read and then request a reading.

**Comment by Praveena0989** [comment]
Thanks for your time David. By the way, I like your youtube channel. Keep up the good work.
