### ISSUE TITLE
Had to move HardwareSerial Serial2(2); into void setup to avoid Compile error

### ISSUE THREAD

**Issue by TrullT** [G6EJD/ESP32-Using-Hardware-Serial-Ports#2]
I was getting a over defined Serial error until I moved the definition into the void loop. 

Anyone else?

**Comment by G6EJD** [comment]
Putting the definition into setup or main loop stops it being a global instance, it’s probably being defined elsewhere. ‘Over’ defined ?

**Comment by PureTek-Innovations** [comment]
Fails to compile with the following error message:

"C:\Users\********\AppData\Local\Temp\arduino_cache_67290\core\core_710d35b91fcdeeaec302aea0b8129adf.a(HardwareSerial.cpp.o):(.bss.Serial2+0x0): multiple definition of `Serial2'

sketch\D32_read_hardSerial.ino.cpp.o:(.bss.Serial2+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board ESP32 Dev Module."

If the line "HardwareSerial Serial2(2);" is commented out, it works perfectly.

**Comment by G6EJD** [comment]
Thanks, I've just checked it all, as you say compiles OK once removed, so I've done that.

When 'hardserial' was added to the ESP32 core things changed - clearly.

Thanks for the help in getting this right for others.
