### ISSUE TITLE
ESP32 Serial2 port sends out junk characters

### ISSUE THREAD

**Issue by ramanraja** [G6EJD/ESP32-Using-Hardware-Serial-Ports#5]
Before I call `Serial2.begin(115200)`, the serial port 2 seems to be sending garbage characters continuously. I connected two ESP32s back to back through their serial port pins 16 and 17, cross connected. I use Arduino C++ library.
To test the behavior of the serial port before it is initialized, I deliberately placed a 10 second delay:
```
  void setup() {
    delay(10000);
    Serial2.begin(115200); 
  }
```
Then the sending device continuously sends a 'hello world' string with a 3 second delay. The receiver simply prints the strings:
```
String str;
void loop(){
  while(Serial2.available()) {  
    str = Serial2.readStringUntil('\n');
    Serial.println(str);
  }
}
```
In the 10 seconds the sender remains uninitialized, the receiver keeps printing random characters continuously. After initialization, the communication flow is smooth and orderly.
Such random streams are unexpected, and can cause undefined behavior at the receiver end.

**Comment by G6EJD** [comment]
That's because the pins you've selected are in a tristate and undefined, if you like they are floating. Then when you define the serial port they assume the correct state and operate as required. What software of behaviour were you expecting with uninitialised pins? 
Do you have any experience in microcontroller operations and programming?

**Comment by G6EJD** [comment]
That's because the pins are uninitialised

**Comment by ramanraja** [comment]
Should a digital OUTPUT pin be in an undefined state (tristate) when the software has not yet initialized it? Seems to be risky behavior. I would prefer it to be either high or low by default, and that should be clearly mentioned in the documentation. If not, rockets can be accidentally launched, nuclear reactors can be turned on.. and so on when you power up the device! Better practice would be to set all digital pins to INPUT mode by default. This gives us breathing time to boot up our software and be ready to handle the pin in a predictable way.

**Comment by G6EJD** [comment]
Every microcontroller is identical where GPIO pins are undefined/tristate at startup. For safety critical designs the solution is simple where external pull-down or pull-up resistors are fitted to define the pin state, or alternatively a UART is not read or its buffer content ignored until after the pin states have been designated, which should take no more then a few microseconds after startup if the first thing that's down is to define the input states and switch on the pull-up or down internal resistors.

**Comment by ramanraja** [comment]
May be, my use case is different. I cannot initialize the serial output port immediately on startup. I have a power on self check routine, read configuration settings from Flash etc. Then only I can decide whether or not serial communication feature is to be enabled. Now I have placed a known marker in the data stream, and the receiver ignores all characters before this marker is spotted. But I am uncomfortable that I am merely brushing the problem under the carpet!  Anyway, thanks for the advice.

**Comment by G6EJD** [comment]
You need to modify your hardware to add appropriate pull-down or up resistors, or immediately at startup enable the ESP32 pull down/up resistors on the GPIO ports then you won't get random characters. Turning on the resistors will have no impact on any code.

**Comment by ramanraja** [comment]
For the benefit of future readers of this page facing a similar issue, here are some other practical remedies:
1) As GGEJD suggested, put the serial pin on the sender to INPUT_PULLUP mode at the very beginning.
2) Put the serial pin to OUTPUT mode and write a 0.
3) Introducing a 2 second delay at the start of the receiver program worked in my case.

Hardware based solutions that may work as well:
 4) Using external pull up/pull down resistors on the serial line
 5) Out of band signaling: Use the RTS/CTS pins on ESP32 serial port (or any other digital pins) to communicate readiness between the sender and receiver.
